package com.codexp.fragility.maintenance.usingconcretetypes;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ReportGeneratorTest {

    // If we change the type of Collection we use to store the Strings, we will have to update the tests here.
    // These days, refactoring tools help a lot reducing the maintenance problem generated by this type of test fragility.
    // Nonetheless, imagine the size of your Pull Request that doubles in number of files just because of this.
    // Furthermore, it's always better to depend on something more stable than you.
    @Test
    void should_be_able_to_add_internalID_header() {
        ReportGenerator gen = new ReportGenerator();

        ArrayList<String> result = gen.generateHeaders(true);

        assertEquals(2, result.size());
    }
}
