package com.codexp.fragility.maintenance.usingconcretetypes;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ReportGeneratorTest {

    // These days, refactoring tools help a lot reducing the maintenance problem generated by this type of test fragility.
    // Nonetheless, imagine the size of your Pull Request that doubles in files just because of this.
    @Test
    void testHeaders_Concrete() {
        ReportGenerator gen = new ReportGenerator();

        // The test MUST use ArrayList to compile
        ArrayList<String> result = gen.generateHeaders(true);

        assertEquals(2, result.size());
        assertEquals("Internal_ID", result.get(1));
    }
}
